# Generated by Django 6.0.3 on 2026-03-15 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DNI", models.CharField(max_length=20, unique=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("monedas", models.PositiveIntegerField(default=10)),
                ("mercenarios", models.PositiveIntegerField(default=0)),
                ("es_admin", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "usuarios",
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="Personaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PERSONAJE", "Personaje"),
                            ("GUERRERO", "Guerrero"),
                            ("MAGO", "Mago"),
                            ("ARQUERO", "Arquero"),
                        ],
                        db_index=True,
                        default="PERSONAJE",
                        max_length=20,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("nivel", models.PositiveIntegerField(default=1)),
                ("vida", models.PositiveIntegerField(default=100)),
                ("vida_max", models.PositiveIntegerField(default=100)),
                ("armadura", models.PositiveIntegerField(blank=True, null=True)),
                ("mana", models.PositiveIntegerField(blank=True, null=True)),
                ("precision", models.PositiveIntegerField(blank=True, null=True)),
                ("vivo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personajes",
                        to="app.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "personajes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Batalla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resultado", models.BooleanField(blank=True, null=True)),
                ("fecha_batalla", models.DateTimeField(auto_now_add=True)),
                ("leido", models.BooleanField(default=False)),
                (
                    "personaje_atacante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batallas_como_atacante",
                        to="app.personaje",
                    ),
                ),
                (
                    "personaje_defensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batallas_como_defensor",
                        to="app.personaje",
                    ),
                ),
                (
                    "id_atacante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batallas_como_atacante",
                        to="app.usuario",
                    ),
                ),
                (
                    "id_defensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batallas_como_defensor",
                        to="app.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "batallas",
                "ordering": ["-fecha_batalla"],
            },
        ),
        migrations.CreateModel(
            name="Amigo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ACEPTADA", "Aceptada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "id_amigo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_recibidas",
                        to="app.usuario",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_enviadas",
                        to="app.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "amigos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.AddIndex(
            model_name="personaje",
            index=models.Index(fields=["nombre"], name="personajes_nombre_2495c3_idx"),
        ),
        migrations.AddIndex(
            model_name="personaje",
            index=models.Index(fields=["tipo"], name="personajes_tipo_18654b_idx"),
        ),
    ]
