# Generated by Django 6.0.2 on 2026-03-10 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_usuario",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("contraseña", models.CharField(max_length=255)),
                ("DNI", models.CharField(max_length=20, unique=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("monedas", models.PositiveIntegerField(default=0)),
                ("mercenarios", models.PositiveIntegerField(default=0)),
                ("es_admin", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "usuarios",
                "ordering": ["nombre_usuario"],
            },
        ),
        migrations.CreateModel(
            name="Batalla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resultado", models.BooleanField(blank=True, null=True)),
                ("fecha_batalla", models.DateTimeField(auto_now_add=True)),
                ("leido", models.BooleanField(default=False)),
                (
                    "personaje_atacante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batallas_como_atacante",
                        to="app.personaje",
                    ),
                ),
                (
                    "personaje_defensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batallas_como_defensor",
                        to="app.personaje",
                    ),
                ),
                (
                    "id_atacante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batallas_como_atacante",
                        to="app.usuario",
                    ),
                ),
                (
                    "id_defensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batallas_como_defensor",
                        to="app.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "batallas",
                "ordering": ["-fecha_batalla"],
            },
        ),
        migrations.AddField(
            model_name="personaje",
            name="id_usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personajes",
                to="app.usuario",
            ),
        ),
        migrations.CreateModel(
            name="Amigo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_amigo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agregado_por",
                        to="app.usuario",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amigos",
                        to="app.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "amigos",
                "unique_together": {("id_usuario", "id_amigo")},
            },
        ),
    ]
