# Generated by Django 6.0.2 on 2026-03-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_usuario_batalla_personaje_id_usuario_amigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaje",
            name="vivo",
            field=models.BooleanField(default=True),
        ),
    ]
