# Generated by Django 6.0.2 on 2026-03-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_personaje_vivo'),
    ]

    operations = [
    ]
