from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from app.views import (
    HomeView,
    EnConstruccionView,
    CrearPersonajeView,
    ListaPersonajesView,
    EliminarPersonajeView,
    EditarPersonajeView,
    CombatirView,
    EntrenarPersonajeView,
)
from app.views import (
    ListaAmigosView,
    BuscarUsuariosView,
    EnviarSolicitudView,
    AceptarSolicitudView,
    RechazarSolicitudView,
    EliminarAmigoView,
)
from app.views import (
    RetarUsuarioView,
    HistorialRetosView,
)

urlpatterns = [
    path("", login_required(HomeView.as_view()), name="home"),
    path(
        "en-construccion/",
        login_required(EnConstruccionView.as_view()),
        name="en_construccion",
    ),
    path(
        "personajes/crear/",
        login_required(CrearPersonajeView.as_view()),
        name="crear_personaje",
    ),
    path(
        "personajes/",
        login_required(ListaPersonajesView.as_view()),
        name="lista_personajes",
    ),
    path(
        "personajes/<int:personaje_id>/editar/",
        login_required(EditarPersonajeView.as_view()),
        name="editar_personaje",
    ),
    path(
        "personajes/<int:personaje_id>/eliminar/",
        login_required(EliminarPersonajeView.as_view()),
        name="eliminar_personaje",
    ),
    path(
        "combate/",
        login_required(CombatirView.as_view()),
        name="combate",
    ),
    path(
        "entrenar/",
        login_required(EntrenarPersonajeView.as_view()),
        name="entrenar",
    ),
    path(
        "amigos/",
        login_required(ListaAmigosView.as_view()),
        name="lista_amigos",
    ),
    path(
        "amigos/buscar/",
        login_required(BuscarUsuariosView.as_view()),
        name="buscar_amigos",
    ),
    path(
        "amigos/enviar/<int:usuario_id>/",
        login_required(EnviarSolicitudView.as_view()),
        name="enviar_solicitud",
    ),
    path(
        "amigos/aceptar/<int:solicitud_id>/",
        login_required(AceptarSolicitudView.as_view()),
        name="aceptar_solicitud",
    ),
    path(
        "amigos/rechazar/<int:solicitud_id>/",
        login_required(RechazarSolicitudView.as_view()),
        name="rechazar_solicitud",
    ),
    path(
        "amigos/eliminar/<int:amigo_id>/",
        login_required(EliminarAmigoView.as_view()),
        name="eliminar_amigo",
    ),
    path(
        "retos/",
        login_required(RetarUsuarioView.as_view()),
        name="retar_usuario",
    ),
    path(
        "retos/historial/",
        login_required(HistorialRetosView.as_view()),
        name="historial_retos",
    ),
    path(
        "estadisticas/",
        login_required(TemplateView.as_view(template_name="estadisticas/index.html")),
        name="estadisticas",
    ),
]
